/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveMonthYearRouteImport } from './routes/archive.$month.$year'
import { Route as ArchiveCompareABRouteImport } from './routes/archive.compare.$a.$b'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveMonthYearRoute = ArchiveMonthYearRouteImport.update({
  id: '/archive/$month/$year',
  path: '/archive/$month/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveCompareABRoute = ArchiveCompareABRouteImport.update({
  id: '/archive/compare/$a/$b',
  path: '/archive/compare/$a/$b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/archive/': typeof ArchiveIndexRoute
  '/archive/$month/$year': typeof ArchiveMonthYearRoute
  '/archive/compare/$a/$b': typeof ArchiveCompareABRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/archive': typeof ArchiveIndexRoute
  '/archive/$month/$year': typeof ArchiveMonthYearRoute
  '/archive/compare/$a/$b': typeof ArchiveCompareABRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/archive/': typeof ArchiveIndexRoute
  '/archive/$month/$year': typeof ArchiveMonthYearRoute
  '/archive/compare/$a/$b': typeof ArchiveCompareABRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/feedback'
    | '/settings'
    | '/tasks'
    | '/archive/'
    | '/archive/$month/$year'
    | '/archive/compare/$a/$b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/feedback'
    | '/settings'
    | '/tasks'
    | '/archive'
    | '/archive/$month/$year'
    | '/archive/compare/$a/$b'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/feedback'
    | '/settings'
    | '/tasks'
    | '/archive/'
    | '/archive/$month/$year'
    | '/archive/compare/$a/$b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ArchiveMonthYearRoute: typeof ArchiveMonthYearRoute
  ArchiveCompareABRoute: typeof ArchiveCompareABRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$month/$year': {
      id: '/archive/$month/$year'
      path: '/archive/$month/$year'
      fullPath: '/archive/$month/$year'
      preLoaderRoute: typeof ArchiveMonthYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/compare/$a/$b': {
      id: '/archive/compare/$a/$b'
      path: '/archive/compare/$a/$b'
      fullPath: '/archive/compare/$a/$b'
      preLoaderRoute: typeof ArchiveCompareABRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ArchiveMonthYearRoute: ArchiveMonthYearRoute,
  ArchiveCompareABRoute: ArchiveCompareABRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
